ajuste

diff --git a/.github/workflows/test_quality.yml b/.github/workflows/test_quality.yml
--- a/.github/workflows/test_quality.yml
+++ b/.github/workflows/test_quality.yml
@@ -53,24 +53,25 @@ jobs:
         fi
 
   unit:
-    - name: Run tests
+    runs-on: ubuntu-latest
+    needs: testBdd
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-      
-    - name: Install dependencies
-      run: npm install
-      
-    - name: Run unit tests
-      run: npm test -- --coverage
-    - name: Check coverage
-      run: |
-        COVERAGE=$(npx istanbul check-coverage --statement 80 --function 80 --lines 80 coverage/coverage-final.json)
-        echo "$COVERAGE"
-        if [[ "$COVERAGE" != *"All thresholds met"* ]]; then
-          echo "Coverage below threshold. Aborting deploy."
-          exit 1
-        else
-          echo "Cobertura de teste unitarios atingidas"
-          exit 0
-        fi
+      - name: Checkout code
+        uses: actions/checkout@v2
+        
+      - name: Install dependencies
+        run: npm install
+        
+      - name: Run unit tests
+        run: npm test -- --coverage
+      - name: Check coverage
+        run: |
+          COVERAGE=$(npx istanbul check-coverage --statement 80 --function 80 --lines 80 coverage/coverage-final.json)
+          echo "$COVERAGE"
+          if [[ "$COVERAGE" != *"All thresholds met"* ]]; then
+            echo "Coverage below threshold. Aborting deploy."
+            exit 1
+          else
+            echo "Cobertura de teste unitarios atingidas"
+            exit 0
+          fi
