Ajustes

diff --git a/.github/workflows/test_quality.yml b/.github/workflows/test_quality.yml
--- a/.github/workflows/test_quality.yml
+++ b/.github/workflows/test_quality.yml
@@ -9,7 +9,7 @@ on:
       - main
 
 jobs:
-  test:
+  testBdd:
     runs-on: ubuntu-latest
 
     steps:
@@ -27,7 +27,7 @@ jobs:
         sudo apt-get install jq
 
     - name: Executar testes BDD e gerar relatório de cobertura
-      run: npm run test
+      run: npm run bdd
 
     - name: Ler informações de cobertura
       run: |
@@ -43,7 +43,7 @@ jobs:
         cobertos=$(cat cobertura.json | jq '.[].lines.hit' | paste -sd+ - | bc)
         percentual=$(echo "scale=2; $cobertos / $coverage * 100" | bc -l)
         echo "Porcentagem de cobertura: $percentual%"
-        pass_percent="80"
+        pass_percent="100"
         if (( $(echo "$percentual >= $pass_percent" | bc -l) )); then
           echo "Cobertura de teste atingida: $percentual%"
           exit 0
@@ -51,3 +51,25 @@ jobs:
           echo "Erro: A cobertura de teste é inferior a $pass_percent% ($percentual%)"
           exit 1
         fi
+  unit:
+    - name: Run tests
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        
+      - name: Install dependencies
+        run: npm install
+        
+      - name: Run unit tests
+        run: npm test -- --coverage
+      - name: Check coverage
+        run: |
+          COVERAGE=$(npx istanbul check-coverage --statement 80 --function 80 --lines 80 coverage/coverage-final.json)
+          echo "$COVERAGE"
+          if [[ "$COVERAGE" != *"All thresholds met"* ]]; then
+            echo "Coverage below threshold. Aborting deploy."
+            exit 1
+          else
+            echo "Cobertura de teste unitarios atingidas"
+            exit 0
+          fi
